version: "3"
services:
  battlebit-server-docker:
    container_name: battlebit-server-docker
    # pull_policy: always
    image: ghcr.io/jackblk/battlebit-server-docker:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./config:/home/steam/config
      - ./data/battlebit:/home/steam/battlebit
      - ./data/Steam:/home/steam/Steam
    env_file:
      - config/.env
    ports:
      - "30000:30000/udp"
      - "30001:30001/udp"
  battlebit-runner:
    container_name: battlebit-runner
    image: ghcr.io/jackblk/battlebit-api-runner:latest
    volumes:
      # - ./config/runner/appsettings.json:/app/appsettings.json
      - ./config/runner/data:/app/data
    # ports:
    #   - "29999:29999"
